apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example-service
  namespace: default
spec:
  ports:
    - name: web-port
      nodePort: 30008
      port: 8888
  selector:
    app: example
  type: NodePort
